name: AutoSpectator
version: "1.0"
main: com.autospectator.plugin.Main
api-version: 1.20
api: "1.20"
description: Automated spectator plugin for recording.
author: SaidTorres3
commands:
  autospectate:
    description: Toggle auto-spectator mode or configure settings.
    usage: /autospectate [player|time|auto] [value]
    permission: autospectator.use
permissions:
  autospectator.use:
    description: Allows use of the autospectate command.
    default: op
